name: Go

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.20

    - id: Build
      name: Build
      run: go build

    - id: Test
      name: Test
      run: go test
    
    - id: Deploy
      uses: google-github-actions/deploy-cloud-functions@main
      with:
        project_id: solar3-301918
        name: solar3_github
        runtime: go120
        entry_point: Solar3 
        env_vars: ${{ secrets.ENV_VARS }} 
        credentials: ${{ secrets.GCP_CRED }}
